export enum STORES_SORTS {
  MOST_RELEVANT = "MOST_RELEVANT",
  HIGHEST_SCORE = "HIGHEST_SCORE",
  LOWEST_SCORE = "LOWEST_SCORE",
  MOST_EXPERIENCES = "MOST_EXPERIENCES",
}

export enum EXPERIENCES_SORTS {
  MOST_RELEVANT = "MOST_RELEVANT",
  NEWEST = "NEWEST",
  HIGHEST_SCORE = "HIGHEST_SCORE",
  LOWEST_SCORE = "LOWEST_SCORE",
}
